# -*- coding: utf-8 -*-
"""Calculadora inteligente.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ytZXBnP1_TsgXiHm1K5xIwKXwKpLxC85
"""

#===========VARIAVEIS============
Lista = 'PASSAR_PAGINA Soma Subtração multiplicação divisao potencia contagem raiz porcentagem inteiro Fatorial Primo Verificar_triangulo Area_Triangulo Area_Quadrado'
Listas = Lista.split()
Lista1 = 'Historico Memoria Voltar'
Lista1 = Lista1.split()
temp2 = []
hist = {}
temp1 = [0]
temp = 0
confirm = 'S'
confirm1 = 0

#============Funções de retorno============
def Soma():
  a = int(input('Insira o Primeiro Valor'))
  b = int(input('Insira o Segundo Valor'))
  S = a+b 
  print(S)
  return (S)


def Subtracao():
  a = int(input('Insira o Primeiro Valor'))
  b = int(input('Insira o Segundo Valor'))
  S = a-b
  print(S)
  return (S)


def multiplicacao():
  a = int(input('Insira o Primeiro Valor'))
  b = int(input('Insira o Segundo Valor'))
  S = a*b
  print(S)
  return (S)


def divisao():
  a = int(input('Insira o Primeiro Valor'))
  b = int(input('Insira o Segundo Valor'))
  S = a/b
  print(S)
  return (S)


def potencia():
  a = int(input('Insira o Primeiro Valor'))
  b = int(input('Insira o Segundo Valor'))
  if b is not int:
    b = 2
  S = a**b
  print(S)
  return (S)


def contagem():
  a = int(input('Valor inicial'))
  b = int(input('Valor Final')) 
  c = int(input('Passo')) 
  if a > b:
    for c in range(a,b-1,c*-1):
      print(c)
  else:
    for c in range(a,b+1,c):
      print(c)
  return c


def raiz():
  a = int(input('Insira o Valor'))
  B = int(input('Quer tirar a Raiz de quanto?'))
  S = a ** (1/B)
  print(S)
  return (S)


def porcent():
  a = int(input('Insira o Primeiro Valor'))
  b = int(input('Insira o Segundo Valor'))  
  S =(a/100)*b
  print(f'{S:.2f}')
  return (S)

def Int():
  a = int(input('Qual numero que deseja verificar'))
  if a%2 == 0:
    print(f'O Numero {a} e inteiro')
  else:
    print(f'O numero {a} Não e inteiro')
  return (a)

def fatorial():
  a = int(input('Insira o Valor que quer tirar fatorial'))
  b = 1
  for c in range(a,b-1,-1):
    print(f'{c}',end=' ')
    if c >1:
      print(f'x',end=' ')
    S*= c
  print(f'= {S}')
  return (S)

  
#==========Funções de Verificar==========
def Primo():
  a = int(input('Insira um numero para verificar se e primo'))
  mult = 0
  for c in range(2,a):
    if a%c == 0:
      print(f'{c}', end=' x ')
      mult+= 1
  if mult == 0:
    print('Numero primo')
  else:
    print('Não e primo')
  

def verificar_triangulo():
    a = int(input('Insira o Primeiro Lado '))
    b = int(input('Insira o Segundo Lado '))
    c = int(input('Insira o Terceiro Lado '))
    Lista = [a,b,c]
    Lista.sort()
    if Lista[0]+Lista[1] < Lista[2]:
        print('Não forma triangulo')
    else:
        if a==b==c:
            print('Forma um Triangulo equilatero')
        elif Lista[0]==Lista[1]:
            print('Forma um Triângulo Isósceles')
        elif a!=b!=c:
            print('Forma um Triângulo Escaleno')


def Ltriangulo():
    a = int(input('Insira a Base'))
    b = int(input('Insira a Altura'))
    S = (a*b)/2
    print(f' A area do triangulo e igual a {S}')


def Lquadrado():
  a = int(input('Insira o Primeiro Lado'))
  b = int(input('Insira o Segundo Lado'))
  S = a*b
  if a==b:
    print(f' E um quadrado equilatero com area de {S}')
  else:
    print(f' E um Retangulo com area de {S}')
 

#============ MENU ============
def Menu():
  print(f'{"CALCULADORA":=^25}')
  cont = 1
  for c in range(1,len(Listas)):
    if cont <=9:
      conts = ('0'+str(cont))
    else:
      conts = str(cont)
    cont += 1
    print(f'[{conts}] {Listas[c]:.<20}')
  
  print(f'{"[0] Proxima Pagina":->25}')
  print(f'{"CALCULADORA":=^25}')
  
#======= MENU 2 =============
def Menu2():
  print(f'{"CALCULADORA":=^25}')
  for c,v in enumerate(Lista1):
    print(f'[{c}] {v:.<16}')

#============HISTORICO========
def historico():
  global temp2
  print(f'{"HISTORICO":=^25}')
  for c in range(0,len(temp2)):
    print(f'{c}')
  
  print(f'{"HISTORICO":=^25}')

#===========MEMORIA===========



#=============================
def Escolha():
  while True:
    N1 = int(input('Escolha uma Operação'))
    if N1 <15 and N1>=0:
      print(f'Voce Quer fazer a operação {Listas[N1]} S/N')
      N2 = input('')
    if N2 in 'Ss':
      return N1
    elif N2 in 'Nn':
      pass
    else:
      print('insira um valor valido')

#=============================
def Escolha2():
  while True:
    N1 = int(input('Escolha uma Operação'))
    if N1 <4 and N1>=0:
      print(f'Voce Quer fazer a operação {Lista1[N1]} S/N')
      N2 = input('')
    if N2 in 'Ss':
      return N1
    elif N2 in 'Nn':
      pass
    else:
      print('insira um valor valido')
#===============CODIGO PRINCIPAL==============
while confirm in 'Ss':
  Menu()
  N1 = Escolha()
  if N1 == 0:
    Menu2()
    N1 = Escolha2()
    if N1 == 0:
      print(f'{"PRINT HISTORICO":=^20}')
      for c,v in enumerate(hist):
        print(f'{c+1}: {v}')
      confirm1 += 1
    elif N1 == 1:
      for c in range(1,len(temp1)):
        print(f'{temp1[c]}')
      confirm1 += 1
    elif N1 == 2:
      confirm1 += 1
      break 
  elif N1 == 1:
    temp = Soma()
    hist[f'o resultado da soma'] = temp
  elif N1 == 2:
    temp = Subtracao()
    hist[f'o resultado da subtração'] = temp
  elif N1 == 3:
    temp = multiplicacao()
    hist[f'o resultado da multiplicacao'] = temp
  elif N1 == 4:
    temp = divisao()
    hist[f'o resultado dadivisao'] = temp
  elif N1 == 5:
    temp = potencia()
    hist[f'o resultado da potencia'] = temp
  elif N1 == 6:
    temp = contagem()
    hist[f'o resultado da contagem'] = temp
  elif N1 == 7:
    temp = raiz()
    hist[f'o resultado da raiz'] = temp
  elif N1 == 8:
    temp = porcent()
    hist[f'o resultado da porcentagem'] = temp
  elif N1 == 9:
    temp = Int()
    hist[f'o resultado de inteiro'] = temp
  elif N1 == 10:
    temp = fatorial()
    hist[f'o resultado de fatorial'] = temp
  elif N1 == 11:
    temp = Primo()
    hist[f'o resultado de Primo'] = temp
  elif N1 == 12:
    temp = verificar_triangulo()
    hist[f'o resultado de verificar_triangulo'] = temp
  elif N1 == 13:
    temp = Ltriangulo()
    hist[f'o resultado de Ltriangulo'] = temp
  elif N1 == 14:
    temp = Lquadrado()
    hist[f'o resultado de Lquadrado'] = temp
  while True:
    confirm = input(f'quer salvar {temp} na memoria? S/N')
    if confirm in 'Ss':
      temp1.append(temp)
      break
    else:
      break
  print(hist)
  confirm = input(' DESEJA CONTINUAR S/N').strip()



hist = {}
hist['fruta'] = 1
hist['323'] = 2
print(hist)

